name: dart_web3modal_adapter
description: "A new Flutter plugin project."
version: 0.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  plugin_platform_interface: ^2.0.2
  dart_solana_adapter: ^0.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: DartWeb3modalAdapter
        fileName: dart_web3modal_adapter.dart
  assets:
    - lib/src/dart_web3modal_adapter.min.js

  
